# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python test_application.py
   deploy:
     needs:
       - build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Install Python 3.9
         uses: actions/setup-python@v1
         with:
              python-version: "3.9"
       - name: Get EB CLI version
         run: |
           python -m pip install --upgrade pip
           pip install awsebcli --upgrade
           eb --version
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ASIAQUZ4GWGOMDEFCXWH
           aws-secret-access-key: rJDijXSBrfsyBHuajjuORkUVr0/t6pOvqq8Fvu6h
           aws-default-region: us-east-1
       - name: Init EB CLI
         run: |
           eb init -p python-3.8 Flask_Basic --region us-east-1
       - name: Create Test Environment and Deploy to Elastic Beanstalk
         run: |
           (eb use test-environment && eb status test-environment && eb deploy) || eb create test-environment
